spring.jackson.mapper.default-view-inclusion=true

jwt.secret=984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
jwt.lifetime=86400000

server.port=8443
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=tomcat

server.http.port=8080