spring.jackson.mapper.default-view-inclusion=true

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=task6
spring.datasource.password=task6